sylius_resource:
  resources:
    ticket_bundle.ticket_product:
      driver: doctrine/orm
      classes:
        model: mztx\TicketBundle\Entity\TicketProduct

    ticket_bundle.ticket_template:
      driver: doctrine/orm
      classes:
        model: mztx\TicketBundle\Entity\TicketTemplate
